parser: Handle comments
Plans can contain comments within resources or immediately after the comment
describing the resource being added/deleted/updated.

Currently, this leads to errors such as:

> Error: unexpected line while parsing resource attribute: # (depends on a resource or a module with changes pending)

The `IsComment` case has been relegated to the final check so that any specific
comment handling can occur before it.

The change to `IsResourceCommentLine` slightly increases strictness, especially
useful if more specific comments are added or considered significant.